Repository dev8-tema4/festival, pull requests merged in 2024-03, with the labels that each got.

#6 Feat/chatting
  CSS/chatting/index.css
  CSS/gyeongki/index.css
  HTML/chatting/index.html
  HTML/gyeongki/index.html
  JS/chatting/index.js
  JS/connSocket.js
  JS/gyeongki/index.js
  JS/user/login.js
  image/chatting/chatIcon.png
Labels: enhancement

#8 Feat/user
  HTML/user/index.html
  HTML/user/login.html
  JS/connSocket.js
  JS/user/login.js
  JS/user/signup.js
  Server/WebSocketServer/src/festival/db/dao/MemberDao.java
  Server/WebSocketServer/src/festival/dto/MemberDto.java
  Server/WebSocketServer/src/festival/server/FestivalWebSocketServer.java
  Server/WebSocketServer/src/festival/server/function/Login.java
  Server/WebSocketServer/src/festival/server/function/Member.java
  Server/WebSocketServer/src/festival/server/function/SignUp.java
Labels: duplicate

#9 F/feat:전라도상세페이지완료
  .gitignore
  CSS/jeonla/index.css
  HTML/jeonla/detailFestival1.html
  HTML/jeonla/detailFestival2.html
  HTML/jeonla/detailFestival3.html
  HTML/jeonla/index.html
  JS/jeonla/detail.js
  JS/jeonla/index.js
Labels: enhancement

#11 F/feat:충청도 html,css 추가
  CSS/chungcheung/index.css
  HTML/chungcheung/index.html
Labels: enhancement

#13 B/FEAT : 주문 및 장바구니 추가
  Server/WebSocketServer/src/festival/db/dao/ItemDao.java
  Server/WebSocketServer/src/festival/db/dao/OrderItemDao.java
  Server/WebSocketServer/src/festival/db/dao/OrdersDao.java
  Server/WebSocketServer/src/festival/dto/ItemDto.java
  Server/WebSocketServer/src/festival/dto/OrderItemDto.java
  Server/WebSocketServer/src/festival/dto/OrdersDto.java
  Server/WebSocketServer/src/festival/server/FestivalWebSocketServer.java
  Server/WebSocketServer/src/festival/server/function/OrderItem.java
  Server/WebSocketServer/src/festival/server/function/Orders.java
Labels: enhancement

#14 B/FIX : 주문할 때 orderId값이 DB값이랑 안 맞는 오류 해결
  Server/WebSocketServer/src/festival/db/dao/OrderItemDao.java
  Server/WebSocketServer/src/festival/db/dao/OrdersDao.java
  Server/WebSocketServer/src/festival/server/FestivalWebSocketServer.java
  Server/WebSocketServer/src/festival/server/function/OrderItem.java
  Server/WebSocketServer/src/festival/server/function/Orders.java
Labels: bug

#15 B/FEAT : 장바구니 기능 추가
  Server/WebSocketServer/src/festival/db/dao/OrderItemDao.java
  Server/WebSocketServer/src/festival/db/dao/OrderResponseDto.java
Labels: enhancement

#17 f/feat:경상도 축제 상세페이지 작성
  HTML/gyungsang/gyungsang_detail.html
  image/gyungsang/eworld-bg.jpg
  image/gyungsang/eworld.png
Labels: enhancement

#18 B/FEAT : 장바구니 and 주문내역 JSON형태 변경
  Server/WebSocketServer/src/festival/db/dao/CartResponseDto.java
  Server/WebSocketServer/src/festival/db/dao/OrderItemDao.java
  Server/WebSocketServer/src/festival/dto/OrderListResponseDto.java
  Server/WebSocketServer/src/festival/server/FestivalWebSocketServer.java
  Server/WebSocketServer/src/festival/server/function/OrderItem.java
Labels: enhancement

#22 B/FEAT : orderId 가져오는 방식 변경 및 memberId 검증
  Server/WebSocketServer/src/festival/db/dao/OrdersDao.java
  Server/WebSocketServer/src/festival/dto/OrdersDto.java
  Server/WebSocketServer/src/festival/server/FestivalWebSocketServer.java
  Server/WebSocketServer/src/festival/server/function/OrderItem.java
  Server/WebSocketServer/src/festival/server/function/Orders.java
Labels: bug, enhancement

#23 F/feat:상점 및 장바구니 css,html (90%)완성
  CSS/chungcheung/index.css
  CSS/shop/order.css
  CSS/shop/order2.css
  HTML/chatting/index.html
  HTML/shop/order.html
  HTML/shop/order2.html
  image/chungcheung/mainBackground2.jpg
  image/chungcheung/mainBackground3.jpg
  image/chungcheung/watercolor-colorful-floral-background_23-2149146553.jpg
  image/shop/bitCamp-removebg-preview.png
  image/shop/cart-removebg-preview.png
  image/shop/equal.png
  image/shop/fresh.jpg
  image/shop/plus.png
  image/shop/prod1.jpg
  image/shop/prod2.jpg
  image/shop/prod3.jpg
  image/shop/prod4.jpg
  image/shop/prod5.jpg
  image/shop/prod6.jpg
Labels: enhancement

#25 Feat, Back/feat:게시판 글 분류 및 검색 기능
  HTML/board/index.html
  JS/board/index.js
  JS/board/list.js
  JS/board/view.js
  JS/board/write.js
  JS/connSocket.js
  Server/WebSocketServer/src/festival/db/dao/BoardDao.java
  Server/WebSocketServer/src/festival/dto/BoardDto.java
  Server/WebSocketServer/src/festival/server/FestivalWebSocketServer.java
  Server/WebSocketServer/src/festival/server/function/Board.java
Labels: enhancement

#26 B/Fix : 장바구니 조회 오류 1차해결 및 itemId검증
  Server/WebSocketServer/src/festival/db/dao/CartResponseDto.java
  Server/WebSocketServer/src/festival/db/dao/ItemDao.java
  Server/WebSocketServer/src/festival/db/dao/MemberDao.java
  Server/WebSocketServer/src/festival/db/dao/OrderItemDao.java
  Server/WebSocketServer/src/festival/db/dao/OrdersDao.java
  Server/WebSocketServer/src/festival/dto/OrderListResponseDto.java
  Server/WebSocketServer/src/festival/server/FestivalWebSocketServer.java
  Server/WebSocketServer/src/festival/server/function/OrderItem.java
  Server/WebSocketServer/src/festival/server/function/Orders.java
Labels: bug, enhancement

#28 B/Fix : 장바구니 조회 오류 2차해결
  Server/WebSocketServer/src/festival/db/dao/CartResponseDto.java
  Server/WebSocketServer/src/festival/db/dao/MemberDao.java
  Server/WebSocketServer/src/festival/db/dao/OrderItemDao.java
  Server/WebSocketServer/src/festival/dto/OrderListResponseDto.java
  Server/WebSocketServer/src/festival/server/FestivalWebSocketServer.java
  Server/WebSocketServer/src/festival/server/function/OrderItem.java
Labels: bug
